/* ============================================================
   Photography catalog — local asset paths. Ordered for visual
   variety: same client/shoot never consecutive.
   orient: "p" portrait | "l" landscape
   ============================================================ */
window.GALLERY = [

  // — Art Direction (posters lead, then campaign mix) —
  { file: "Category Faves/ART DIRECTION/VonDutchPosters.jpg",                  client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/VonDutchPostersss.jpg",                client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/VonDutch4thhh.jpg",                    client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/Von Dutch 4th.jpg",                    client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/VonDutchRanch2.jpg",                   client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/SnapInsta-Ai_3667353724793402401.jpg", client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/VonDutchRanch3.jpg",                   client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/SnapInsta-Ai_3686199603596098000.jpg", client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/VonDutchRanch4.jpg",                   client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/VonDutchRanch5.jpg",                   client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/SnapInsta-Ai_3686199603906433860.jpg", client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/DSCF9913.jpg",                         client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/SnapInsta-Ai_3686199603906475001.jpg", client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/VonDutchRanch7.jpg",                   client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/SnapInsta-Ai_3686199603923026200.jpg", client: "Von Dutch",        tag: "Art Direction", orient: "p" },
  { file: "Category Faves/ART DIRECTION/VonDutchRanch9.jpg",                   client: "Von Dutch",        tag: "Art Direction", orient: "p" },

  // — Creative Production (interleaved — no same brand adjacent) —
  { file: "Category Faves/CREATIVE PRODUCTION/EdHardySwim1.jpg",            client: "Ed Hardy Swim",    tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch8.jpg",               client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch9.jpg",               client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch10.jpg",              client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/EdHardySwim2.jpg",            client: "Ed Hardy Swim",    tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch11.jpg",              client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch12.jpg",              client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/Asteroidolf2.jpg",            client: "Asteroidolf",      tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch13.jpg",              client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/EdHardySwim3.jpg",            client: "Ed Hardy Swim",    tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch21.jpg",              client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch23.jpg",              client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/EdHardySwim4.jpg",            client: "Ed Hardy Swim",    tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch24.jpg",              client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/LoveWar5.jpg",               client: "Love + War",       tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch25.jpg",              client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/Asteroidolf5.jpg",            client: "Asteroidolf",      tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/EdHardySwim5.jpg",            client: "Ed Hardy Swim",    tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/LoveWar6.jpg",               client: "Love + War",       tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/VonDutch29.jpg",              client: "Von Dutch",        tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/LoveWar7.jpg",               client: "Love + War",       tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/EdHardySwimLifestyle0140.jpg",client: "Ed Hardy Swim",    tag: "Creative Production", orient: "l" },
  { file: "Category Faves/CREATIVE PRODUCTION/Ed HArdy Swim .jpg",          client: "Ed Hardy Swim",    tag: "Creative Production", orient: "p" },
  { file: "Category Faves/CREATIVE PRODUCTION/Von Dutch Swim.jpg",          client: "Von Dutch",        tag: "Creative Production", orient: "p" },

  // — Photography (best range first — commercial, celebrity, music, then fashion, intimates last) —

  // strong opens: movie poster, Vans, Stella Rosa, male/female mix
  { file: "photo/SemblanceCover.jpeg",                                                           client: "Semblance · Movie Poster",         tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/VansRexRaiven97.jpg",                                           client: "Vans x T-Rex Global",              tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/STELLA ROSA BRANDY0000.jpg",                                    client: "Stella Rosa · Brandy",             tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/DiegoBoxing40.jpg",                                             client: "Diego A",                          tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/VansForCoverPage.webp",                                         client: "Vans x T-Rex Global",              tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/BRANDY 2.JPG",                                                  client: "Stella Rosa · Brandy Gordon",      tag: "Photography", orient: "p" },
  { file: "photo/Magazine Cover  .webp",                                                         client: "Shagmag · Lottie Moss",            tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/vans shoes 2.webp",                                             client: "Vans x T-Rex Global",              tag: "Photography", orient: "l" },
  { file: "Category Faves/PHOTO/MISFITZMAG.jpg",                                                client: "MISFITZMAG · Julia Rose",          tag: "Photography", orient: "p" },
  { file: "photo/JosephChilliamsEP.jpg",                                                         client: "Joseph Chilliams · EP",            tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/VansRexRaiven29.jpg",                                           client: "Vans x T-Rex Global",              tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/STELLA ROSA BRANDY0001.jpg",                                    client: "Stella Rosa · Brandy",             tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/SabZadaMISFITZMAG7 (1).jpg",                                   client: "MISFITZMAG · Sab Zada",            tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Duckworthmusicvideo.webp",                                      client: "Duckwrth · Music Video",           tag: "Photography", orient: "l" },

  // editorial & celebrity — interleaved, no same client adjacent
  { file: "Category Faves/PHOTO/LottieGarden0000.JPG",                                          client: "Lottie Moss",                      tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/MISFITZMAG1.jpg",                                               client: "MISFITZMAG",                       tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Shagmag.jpg",                                                   client: "Shagmag",                          tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/JuliaKHeart-(1of18).jpg",                                       client: "Julia Kelly · UTS",                tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/DiegoBoxing122.jpg",                                            client: "Diego A",                          tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/MABASHFeb2026425.jpg",                                          client: "MABASH",                           tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/LottieGarden0003.JPG",                                          client: "Lottie Moss · Garden",             tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Shagmag_BrandyG_Look5_1664.jpg",                                client: "Shagmag · Brandy Gordon",          tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/JuliaKHeart-(9of18).jpg",                                       client: "Julia Kelly · UTS",                tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/DUCKWORTH-POWER-DUCK-SOLO 16.jpg",                              client: "Duckwrth · Music Video",           tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/MABASHFeb2026611.jpg",                                          client: "MABASH",                           tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/LottieGarden0005.jpeg",                                         client: "Lottie Moss · Garden",             tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/MISFITZMAG5.jpg",                                               client: "MISFITZMAG",                       tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/HaydenStairs 40 (1).JPG",                                       client: "Hayden Graye",                     tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/HermanNovember270.jpg",                                         client: "Herman Ghambir",                   tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Brandy Gordon.JPG",                                             client: "Stella Rosa · Brandy Gordon",      tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Mabash08-15-25-1_(3).jpg",                                      client: "MABASH",                           tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/LottieGarden0006.jpeg",                                         client: "Lottie Moss · Garden",             tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Saraga Artist Press.jpg",                                       client: "Saraga · Artist Press",            tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/SOULA-SHAGMAG0005.JPG",                                         client: "Shagmag · Soula Rouge",            tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/HermanNovember290.jpg",                                         client: "Herman Ghambir",                   tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Mabash08-15-25-2_(2).jpg",                                      client: "MABASH",                           tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/LottieMossss.jpeg",                                             client: "Lottie Moss",                      tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/JuliaKHeart-(11of18).jpg",                                      client: "Julia Kelly · UTS",                tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/CLAUDIA-PICNIC-FILM 56.jpg",                                    client: "Claudia Tihan",                    tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/EveryoneTV 9 (1).JPG",                                          client: "Hayden Graye",                     tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/TimMaxeyFeb51.jpg",                                             client: "Tim Maxey · Artist Press",         tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Mabash08-15-25-9_(2).jpg",                                      client: "MABASH",                           tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/LottiePastelRoom 31.jpg",                                       client: "Lottie Moss",                      tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/AlCalderonEP.JPG",                                              client: "Al Calderon · EP",                 tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Shagmaggg.JPG",                                                 client: "Shagmag · Brandy Gordon",          tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/JuliaKelly-UTS.jpg",                                            client: "Julia Kelly · UTS",                tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/ClaudiaTihanBed&CakeDigital9737.jpg",                           client: "Claudia Tihan",                    tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Mabash08-15-25-11_(2).jpg",                                     client: "MABASH",                           tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Brandy 5.JPG",                                                  client: "Shagmag · Brandy Gordon",          tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/LottiePastelRoom 38.jpg",                                       client: "Lottie Moss",                      tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/BellaSaintclaire.jpg",                                          client: "Bella Saintclaire",                tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Mabash08-15-25-12_(2).jpg",                                     client: "MABASH",                           tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/SabZadaMISFITZMAG29.jpg",                                       client: "MISFITZMAG · Sab Zada",            tag: "Photography", orient: "p" },

  // portrait, events, fashion — interleaved
  { file: "Category Faves/PHOTO/Heloise Hut.jpg",                                               client: "Heloise Hutt",                     tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/TiffanyBeach1.png",                                             client: "Tiffany Keller",                   tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/FashionFaye Dreamgirl.webp",                                    client: "Faye Dreamgirl",                   tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Activewear-VonDutch.jpg",                                       client: "Von Dutch",                        tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/RoverHatSammy29.png",                                           client: "Visibly Toxic",                    tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/EmilySumba34.png",                                              client: "Emily Sumba",                      tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/IGNITE0000.JPG",                                                client: "Ignite Vape",                      tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/HeloiseHutt.JPG",                                               client: "Heloise Hutt",                     tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/CamiStrellaFeb-(93of120).jpg",                                  client: "Cami Strella",                     tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/RAIN ROOM0001 (1).jpeg",                                        client: "Rain Room",                        tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Fashion. Faye Dreamgirl.webp",                                  client: "Faye Dreamgirl",                   tag: "Photography", orient: "l" },
  { file: "Category Faves/PHOTO/VDBlackFriday 422.jpg",                                         client: "Von Dutch",                        tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/AshleyG12 (1).jpg",                                             client: "Ashley Graves Ramybrooke",         tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Elisha Herbert TOAST BTS.webp",                                 client: "Elisha Herbert · Toast",           tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/VisiblyToxic.png",                                              client: "Visibly Toxic",                    tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/EmmaPillQuips 14.jpg",                                          client: "Emma Pill x Quips",                tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Ignite - Biniki Brand  .webp",                                  client: "Ignite · Swim",                    tag: "Photography", orient: "l" },
  { file: "Category Faves/PHOTO/Add DJ BTS - Jaden Thompson Reframe Opening  .webp",            client: "Jaden Thompson · Reframe Opening", tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/FayeDreamgirl.PNG",                                             client: "Faye Dreamgirl",                   tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/TiffanyBeach31.png",                                            client: "Tiffany Keller",                   tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/JuliaRoseSpeed66.jpg",                                          client: "Speed Suspects · Julia Rose",      tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/ZaharaNenekBlackBronze 99.jpg",                                 client: "Zahara Davis",                     tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Concert - Alesso & John Alto at The Brooklyn Yards  .webp",     client: "Alesso · Brooklyn Yards",          tag: "Photography", orient: "l" },
  { file: "Category Faves/PHOTO/FayeDreamgirlFashionShow.png",                                  client: "Faye Dreamgirl · Fashion Show",    tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/RuckusartistPressss.jpg",                                       client: "Ruckus · Artist Press",            tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Umansky Family- Events.jpg",                                    client: "Umansky Family · Events",          tag: "Photography", orient: "l" },
  { file: "Category Faves/PHOTO/fashion.webp",                                                  client: "Zara Davis",                       tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Group Travel - Bali .webp",                                     client: "Travel · Bali",                    tag: "Photography", orient: "l" },
  { file: "Category Faves/PHOTO/Premium Content  .webp",                                        client: "Faustina Fernandez",               tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Magazine Editorial  .webp",                                     client: "Shagmag · Brandy Gordon",          tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Magazine Editorial  2.webp",                                    client: "MISFITZMAG · Julia Rose",          tag: "Photography", orient: "l" },

  // intimate / lingerie — kept toward the end
  { file: "Category Faves/PHOTO/Intimates- OW Intimates  .webp",                                client: "OW Intimates",                     tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Intimates - Gooseberry  .webp",                                 client: "Olivia Blais · Gooseberry Intimates", tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/OW.jpg",                                                        client: "OW",                               tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/Intimates - Culprit  .webp",                                    client: "Culprit",                          tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/OW111.jpg",                                                     client: "OW",                               tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/LivBlaisGOF0001.jpeg",                                          client: "Olivia Blais · Gooseberry Intimates", tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/ReneeOW0013 (1).jpg",                                           client: "OW Intimates",                     tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/LivBlaisGOF0008.jpeg",                                          client: "Olivia Blais · Gooseberry Intimates", tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/BlackCorsetDress42.jpg",                                        client: "OW",                               tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/BlackCorsetHalter13.jpg",                                       client: "OW",                               tag: "Photography", orient: "p" },
  { file: "Category Faves/PHOTO/LavenderLongDress11.jpg",                                       client: "OW",                               tag: "Photography", orient: "p" },

];
